services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: termbox
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  termbox:
    depends_on:
      - postgres
    image: healthsamurai/termbox:0.10.1-SNAPSHOT
    pull_policy: always
    ports:
      - "7001:3000"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: postgres
      PG_MAINTENANCE_WORK_MEM: 512MB
      LOG_FORMAT: json
      HTTP_BASE_URL: http://localhost:7001
      DATA_CONFIG_FILE: /data/data.yaml
    volumes:
      - ./data.yaml:/data/data.yaml
      - ../../../.tx-content/tx-benchmark:/data/tx-content
volumes:
  postgres_data:
    name: termbox_postgres_data
